### ISSUE TITLE
Pass Paths for Config as Parameters

### ISSUE THREAD

**Issue by mweidling** [MehmedGIT/OtoN_Converter#11]
Currently the paths to e.g. the place where the models are stored are hard coded in `oton/config.toml`.

If I want to use OtoN I have to update these paths to match my system. This is especially cumbersome when I use OtoN as part of a larger script.

It would come in handy if I could pass my own paths to the mets, the models, etc. to OtoN by something like `oton --path-to-mets="/some/path" --path-to-models="/some/other/path"` etc..

**Comment by MehmedGIT** [comment]
@mweidling, sorry for being a bit late to reply - just found some time to check the tool again. After more consideration, I think adding more CLI parameters to the OtoN converter to overwrite parameter values in the requested way would overcomplicate the usage of the tool. The idea behind this tool was to provide easy conversion from OCR-D workflows to Nextflow workflows.

Suggestion: When executing the Nextflow script you can always pass another value from the CLI, i.e., `nextflow run <script_name> --mets_path=<path> --models_path=<path>`. 

I am currently considering simplifying the produced Nextflow scripts by completely removing the clumsy usage of `params.workspace_path` and having just the `params.mets_path = "mets.xml"`,i.e., the current directory. By definition, the workspace folder is always in the same directory as the mets file. So having the mets file path is enough. I would also like to get rid of `\$HOME` and `$projectDir` since they can get confusing.

PS: I have created a version tag v0.0.1 of the current state of the converter. You can always rely on that version if something breaks on your side after I do some potentially breaking changes.

**Comment by mweidling** [comment]
> Suggestion: When executing the Nextflow script you can always pass another value from the CLI, i.e., `nextflow run <script_name> --mets_path=<path> --models_path=<path>`.

This would be fine for my use case.

> I would also like to get rid of `\$HOME` and `$projectDir` since they can get confusing.

Indeed, they confuse me time and time again. I'm looking forward to seeing them replaced orgone.


> PS: I have created a version tag v0.0.1 of the current state of the converter. You can always rely on that version if something breaks on your side after I do some potentially breaking changes.

Thank you, this will come in handy! :)
